http:
  host: 0.0.0.0
  port: 34567
database:
  host: gm-postgres
  port: 5432
  username: GpuManager
  password: GpuManager
  database: GpuManager
redis:
  host: ms-redis
  port: 6379
system:
  verify: false
